// export enum GunplaGrade {
//   OTHER = 'other',
//   NG = 'NG',
//   SD = 'SD',
//   EG = 'EG',
//   HG = 'HG',
//   RG = 'RG',
//   MG = 'MG',
//   PG = 'PG',
//   RE100 = 'RE100',
//   FM = 'FM',
//   MGSD = 'MGSD',
//   MEGA = 'MEGA',
// }

// export enum MsrpCurrency {
//   THB = 'THB',
//   JPY = 'JPY',
//   CNY = 'CNY',
//   USD = 'USD',
// }

// export enum GunplaExclusivity {
//   NONE = 'none',
//   GUNDAM_BASE_LIMITED = 'gundam_base_limited',
//   P_BANDAI = 'p_bandai',
//   EVENT = 'event',
//   SPECIAL_PACHAGE = 'special_package',
// }

// export enum LiquidProductType {
//   OTHER = 'other',
//   PAINT = 'paint',
//   PRIMER = 'primer',
//   SOLVENT = 'solvent',
//   THINNER = 'thinner',
//   CEMENT = 'cement',
// }

// export enum ResinType {
//   NONE = 'none',
//   ACRYLIC = 'acrylic',
//   LACQUER = 'lacquer',
//   ENAMEL = 'enamel',
//   EPOXY = 'epoxy',
// }

// export enum ColorTone {
//   OTHER = 'other',
//   RED = 'red',
//   ORANGE = 'orange',
//   YELLOW = 'yellow',
//   GREEN = 'green',
//   CYAN = 'cyan',
//   BLUE = 'blue',
//   PURPLE = 'purple',
//   BLACK = 'black',
//   WHITE = 'white',
//   GRAY = 'gray',
//   PINK = 'pink',
//   BROWN = 'brown',
//   GOLD = 'gold',
//   SILVER = 'silver',
//   COPPER = 'copper',
// }

// export enum PaintSpecialPorperty {
//   NONE = 'none',
//   CLEAR = 'clear',
//   METALIC = 'metalic',
// }

// export enum PaintApplicationMethod {
//   OTHER = 'other',
//   SPRAY = 'spray',
//   BRUSH = 'brush',
//   AIR_BRUSH_READY = 'air_brush_ready',
//   PANEL_LINER = 'panel_liner',
// }

// export enum PaintFinish {
//   OTHER = 'other',
//   GLOSS = 'gloss',
//   SEMI_GLOSS = 'semi_gloss',
//   SATIN = 'satin',
//   MATTE = 'matte',
// }

export enum AdditionalForm {
  FIGURE_COMMON = 'figure_common',
  BANDAI_GUNPLA_DETAIL = 'bandai_gunpla_detail',
  LIQUID_PRODUCT = 'liquid_product',
  PAINT = 'paint',
}

export enum Category {
  OTHER = 1,
  MODEL_KIT = 2,
  GUNPLA = 3,
  FIGURE = 4,
  TOOL = 5,
  LIQUID_PRODUCT = 6,
  PAINT = 7,
}

/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports all enum related types from the schema.
 *
 * 🟢 You can import this file directly.
 */

export const Currency = {
  THB: 'THB',
  JPY: 'JPY',
  CNY: 'CNY',
  USD: 'USD',
} as const

export type Currency = (typeof Currency)[keyof typeof Currency]

export const GunplaGrade = {
  other: 'other',
  NG: 'NG',
  SD: 'SD',
  EG: 'EG',
  HG: 'HG',
  MG: 'MG',
  PG: 'PG',
  RG: 'RG',
  RE100: 'RE100',
  FM: 'FM',
  MGSD: 'MGSD',
  MEGA: 'MEGA',
} as const

export type GunplaGrade = (typeof GunplaGrade)[keyof typeof GunplaGrade]

export const GunplaExclusivity = {
  none: 'none',
  gundam_base_limited: 'gundam_base_limited',
  p_bandai: 'p_bandai',
  event: 'event',
  special_package: 'special_package',
} as const

export type GunplaExclusivity =
  (typeof GunplaExclusivity)[keyof typeof GunplaExclusivity]

export const LiquidProductType = {
  other: 'other',
  paint: 'paint',
  primer: 'primer',
  solvent: 'solvent',
  thinner: 'thinner',
  cement: 'cement',
} as const

export type LiquidProductType =
  (typeof LiquidProductType)[keyof typeof LiquidProductType]

export const ResinType = {
  none: 'none',
  acrylic: 'acrylic',
  lacquer: 'lacquer',
  enamel: 'enamel',
  epoxy: 'epoxy',
} as const

export type ResinType = (typeof ResinType)[keyof typeof ResinType]

export const PaintApplicationMethod = {
  other: 'other',
  spray: 'spray',
  brush: 'brush',
  air_brush_ready: 'air_brush_ready',
  panel_liner: 'panel_liner',
} as const

export type PaintApplicationMethod =
  (typeof PaintApplicationMethod)[keyof typeof PaintApplicationMethod]

export const PaintFinish = {
  other: 'other',
  gloss: 'gloss',
  semi_gloss: 'semi_gloss',
  satin: 'satin',
  matte: 'matte',
} as const

export type PaintFinish = (typeof PaintFinish)[keyof typeof PaintFinish]

export const ColorTone = {
  other: 'other',
  red: 'red',
  orange: 'orange',
  yellow: 'yellow',
  green: 'green',
  cyan: 'cyan',
  blue: 'blue',
  purple: 'purple',
  black: 'black',
  white: 'white',
  gray: 'gray',
  pink: 'pink',
  brown: 'brown',
  gold: 'gold',
  silver: 'silver',
  copper: 'copper',
} as const

export type ColorTone = (typeof ColorTone)[keyof typeof ColorTone]

export const PaintSpecialPorperty = {
  none: 'none',
  clear: 'clear',
  metalic: 'metalic',
} as const

export type PaintSpecialPorperty =
  (typeof PaintSpecialPorperty)[keyof typeof PaintSpecialPorperty]
