/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NotFoundRouteImport } from './routes/not-found'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as appRouteRouteImport } from './routes/(app)/route'
import { Route as appIndexRouteImport } from './routes/(app)/index'
import { Route as authSignupRouteImport } from './routes/(auth)/signup'
import { Route as authSigninRouteImport } from './routes/(auth)/signin'
import { Route as appAddItemRouteImport } from './routes/(app)/add-item'
import { Route as appViewItemIdRouteImport } from './routes/(app)/view-item/$id'
import { Route as appEditItemIdRouteImport } from './routes/(app)/edit-item/$id'

const NotFoundRoute = NotFoundRouteImport.update({
  id: '/not-found',
  path: '/not-found',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const appIndexRoute = appIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appRouteRoute,
} as any)
const authSignupRoute = authSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => authRouteRoute,
} as any)
const authSigninRoute = authSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => authRouteRoute,
} as any)
const appAddItemRoute = appAddItemRouteImport.update({
  id: '/add-item',
  path: '/add-item',
  getParentRoute: () => appRouteRoute,
} as any)
const appViewItemIdRoute = appViewItemIdRouteImport.update({
  id: '/view-item/$id',
  path: '/view-item/$id',
  getParentRoute: () => appRouteRoute,
} as any)
const appEditItemIdRoute = appEditItemIdRouteImport.update({
  id: '/edit-item/$id',
  path: '/edit-item/$id',
  getParentRoute: () => appRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/not-found': typeof NotFoundRoute
  '/add-item': typeof appAddItemRoute
  '/signin': typeof authSigninRoute
  '/signup': typeof authSignupRoute
  '/': typeof appIndexRoute
  '/edit-item/$id': typeof appEditItemIdRoute
  '/view-item/$id': typeof appViewItemIdRoute
}
export interface FileRoutesByTo {
  '/not-found': typeof NotFoundRoute
  '/add-item': typeof appAddItemRoute
  '/signin': typeof authSigninRoute
  '/signup': typeof authSignupRoute
  '/': typeof appIndexRoute
  '/edit-item/$id': typeof appEditItemIdRoute
  '/view-item/$id': typeof appViewItemIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)': typeof appRouteRouteWithChildren
  '/(auth)': typeof authRouteRouteWithChildren
  '/not-found': typeof NotFoundRoute
  '/(app)/add-item': typeof appAddItemRoute
  '/(auth)/signin': typeof authSigninRoute
  '/(auth)/signup': typeof authSignupRoute
  '/(app)/': typeof appIndexRoute
  '/(app)/edit-item/$id': typeof appEditItemIdRoute
  '/(app)/view-item/$id': typeof appViewItemIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/not-found'
    | '/add-item'
    | '/signin'
    | '/signup'
    | '/'
    | '/edit-item/$id'
    | '/view-item/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/not-found'
    | '/add-item'
    | '/signin'
    | '/signup'
    | '/'
    | '/edit-item/$id'
    | '/view-item/$id'
  id:
    | '__root__'
    | '/(app)'
    | '/(auth)'
    | '/not-found'
    | '/(app)/add-item'
    | '/(auth)/signin'
    | '/(auth)/signup'
    | '/(app)/'
    | '/(app)/edit-item/$id'
    | '/(app)/view-item/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appRouteRoute: typeof appRouteRouteWithChildren
  authRouteRoute: typeof authRouteRouteWithChildren
  NotFoundRoute: typeof NotFoundRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/not-found': {
      id: '/not-found'
      path: '/not-found'
      fullPath: '/not-found'
      preLoaderRoute: typeof NotFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)': {
      id: '/(app)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/': {
      id: '/(app)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/signin': {
      id: '/(auth)/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof authSigninRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(app)/add-item': {
      id: '/(app)/add-item'
      path: '/add-item'
      fullPath: '/add-item'
      preLoaderRoute: typeof appAddItemRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/view-item/$id': {
      id: '/(app)/view-item/$id'
      path: '/view-item/$id'
      fullPath: '/view-item/$id'
      preLoaderRoute: typeof appViewItemIdRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/edit-item/$id': {
      id: '/(app)/edit-item/$id'
      path: '/edit-item/$id'
      fullPath: '/edit-item/$id'
      preLoaderRoute: typeof appEditItemIdRouteImport
      parentRoute: typeof appRouteRoute
    }
  }
}

interface appRouteRouteChildren {
  appAddItemRoute: typeof appAddItemRoute
  appIndexRoute: typeof appIndexRoute
  appEditItemIdRoute: typeof appEditItemIdRoute
  appViewItemIdRoute: typeof appViewItemIdRoute
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appAddItemRoute: appAddItemRoute,
  appIndexRoute: appIndexRoute,
  appEditItemIdRoute: appEditItemIdRoute,
  appViewItemIdRoute: appViewItemIdRoute,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

interface authRouteRouteChildren {
  authSigninRoute: typeof authSigninRoute
  authSignupRoute: typeof authSignupRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authSigninRoute: authSigninRoute,
  authSignupRoute: authSignupRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  appRouteRoute: appRouteRouteWithChildren,
  authRouteRoute: authRouteRouteWithChildren,
  NotFoundRoute: NotFoundRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
