/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NotFoundRouteImport } from './routes/not-found'
import { Route as AddItemRouteImport } from './routes/add-item'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ViewItemIdRouteImport } from './routes/view-item/$id'
import { Route as ExampleSignupRouteImport } from './routes/example/signup'
import { Route as ExampleSigninRouteImport } from './routes/example/signin'
import { Route as EditItemIdRouteImport } from './routes/edit-item/$id'

const NotFoundRoute = NotFoundRouteImport.update({
  id: '/not-found',
  path: '/not-found',
  getParentRoute: () => rootRouteImport,
} as any)
const AddItemRoute = AddItemRouteImport.update({
  id: '/add-item',
  path: '/add-item',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ViewItemIdRoute = ViewItemIdRouteImport.update({
  id: '/view-item/$id',
  path: '/view-item/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ExampleSignupRoute = ExampleSignupRouteImport.update({
  id: '/example/signup',
  path: '/example/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ExampleSigninRoute = ExampleSigninRouteImport.update({
  id: '/example/signin',
  path: '/example/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const EditItemIdRoute = EditItemIdRouteImport.update({
  id: '/edit-item/$id',
  path: '/edit-item/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add-item': typeof AddItemRoute
  '/not-found': typeof NotFoundRoute
  '/edit-item/$id': typeof EditItemIdRoute
  '/example/signin': typeof ExampleSigninRoute
  '/example/signup': typeof ExampleSignupRoute
  '/view-item/$id': typeof ViewItemIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add-item': typeof AddItemRoute
  '/not-found': typeof NotFoundRoute
  '/edit-item/$id': typeof EditItemIdRoute
  '/example/signin': typeof ExampleSigninRoute
  '/example/signup': typeof ExampleSignupRoute
  '/view-item/$id': typeof ViewItemIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add-item': typeof AddItemRoute
  '/not-found': typeof NotFoundRoute
  '/edit-item/$id': typeof EditItemIdRoute
  '/example/signin': typeof ExampleSigninRoute
  '/example/signup': typeof ExampleSignupRoute
  '/view-item/$id': typeof ViewItemIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add-item'
    | '/not-found'
    | '/edit-item/$id'
    | '/example/signin'
    | '/example/signup'
    | '/view-item/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add-item'
    | '/not-found'
    | '/edit-item/$id'
    | '/example/signin'
    | '/example/signup'
    | '/view-item/$id'
  id:
    | '__root__'
    | '/'
    | '/add-item'
    | '/not-found'
    | '/edit-item/$id'
    | '/example/signin'
    | '/example/signup'
    | '/view-item/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddItemRoute: typeof AddItemRoute
  NotFoundRoute: typeof NotFoundRoute
  EditItemIdRoute: typeof EditItemIdRoute
  ExampleSigninRoute: typeof ExampleSigninRoute
  ExampleSignupRoute: typeof ExampleSignupRoute
  ViewItemIdRoute: typeof ViewItemIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/not-found': {
      id: '/not-found'
      path: '/not-found'
      fullPath: '/not-found'
      preLoaderRoute: typeof NotFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-item': {
      id: '/add-item'
      path: '/add-item'
      fullPath: '/add-item'
      preLoaderRoute: typeof AddItemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/view-item/$id': {
      id: '/view-item/$id'
      path: '/view-item/$id'
      fullPath: '/view-item/$id'
      preLoaderRoute: typeof ViewItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/example/signup': {
      id: '/example/signup'
      path: '/example/signup'
      fullPath: '/example/signup'
      preLoaderRoute: typeof ExampleSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/example/signin': {
      id: '/example/signin'
      path: '/example/signin'
      fullPath: '/example/signin'
      preLoaderRoute: typeof ExampleSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit-item/$id': {
      id: '/edit-item/$id'
      path: '/edit-item/$id'
      fullPath: '/edit-item/$id'
      preLoaderRoute: typeof EditItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddItemRoute: AddItemRoute,
  NotFoundRoute: NotFoundRoute,
  EditItemIdRoute: EditItemIdRoute,
  ExampleSigninRoute: ExampleSigninRoute,
  ExampleSignupRoute: ExampleSignupRoute,
  ViewItemIdRoute: ViewItemIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
